services:
  - type: web
    name: resilient-email-service-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_RATE_LIMIT
        value: 10
      - key: STATUS_RATE_LIMIT
        value: 60
      - key: MONITORING_RATE_LIMIT
        value: 120
      - key: QUEUE_PROCESS_INTERVAL
        value: 6000
      - key: CIRCUIT_FAILURE_THRESHOLD
        value: 5
      - key: CIRCUIT_TIMEOUT
        value: 60000
      - key: LOG_LEVEL
        value: info
      - key: PROVIDER_A_FAILURE_RATE
        value: 0.3
      - key: PROVIDER_B_FAILURE_RATE
        value: 0.2
      - key: CORS_ORIGIN
        value: https://reilient-email-service.netlify.app
