services:
  - type: web
    name: resilient-email-service-api
    env: node
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production